version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: my-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  api:
    image: dunkbing/anime-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.anime-api.rule=Host("anime-api.mybackhug.com")
      - traefik.http.routers.anime-api.entrypoints=web-secure
      - traefik.http.routers.anime-api.tls=true
      - traefik.http.routers.anime-api.tls.certresolver=letsEncrypt
