version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: my-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
